export const START_BUTTON = 'START_BUTTON'
export const RESET_CARDS = 'RESET_CARDS'
export const CLICK_HANDLER = 'CLICK_HANDLER'
export const OFF_DISABLED = 'OFF_DISABLED'
export const FLIP_HANDLER = 'FLIP_HANDLER'
export const FLIP_BACK = 'FLIP_BACK'
export const ON_SOLVED = 'ON_SOLVED'